//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.Balance = new HashSet<BalanceItem>();
        }
    
        public int ID { get; set; }
        public int BankID { get; set; }
        public string Apelido { get; set; }
        public string Agencia { get; set; }
        public string ContaCorrente { get; set; }
        public string Operacao { get; set; }
        public string Gerente { get; set; }
        public string Telefone { get; set; }
        public string Celular { get; set; }
        public string EMail { get; set; }
    
        public virtual Bank Bank { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BalanceItem> Balance { get; set; }
    }
}
