//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnaliseItem
    {
        public string Ano { get; set; }
        public string Mes { get; set; }
        public string Grupo { get; set; }
        public string Categoria { get; set; }
        public Nullable<decimal> Sinal { get; set; }
        public decimal Valor { get; set; }
        public string Tipo { get; set; }
    }
}
