//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    
    public partial class NextPayment
    {
        public Nullable<System.DateTime> Date { get; set; }
        public string Group { get; set; }
        public Nullable<int> DaysLate { get; set; }
        public string Description { get; set; }
    }
}
